name: Test code and embed into README

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  readme-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: action/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
<<<<<<< HEAD
          python-version: 3.10
=======
          python-version: '3.10'
>>>>>>> 636007d8bd53996121affa12ab107f8795ae9724
      - name: Install dependency
        run: pip install pytest
      - name: Test with pytest
        run: pytest test_src
      - name: Markdown
      - name: Check modified
      - name: Commit files
      - name: Push changes

